def getarchi(nlayers=3,D=15,OUT=4,C1=15,C2=60,C3=20):
    if(nlayers==1):
        ARCHI = ([('input',D),
            ('dense', (C1, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (C1, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ])
    elif(nlayers==2):
        ARCHI = ([('input',D),
            ('dense', (C1, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (C2, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (C2, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (C1, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ])
    elif(nlayers==3):
        ARCHI = ([('input',D),
            ('dense', (C1, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (C2, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (C3, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
        ],[('input' , OUT),
            ('dense', (C3, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (C2, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (C1, 'glorot_uniform', 'glorot_normal') ),
            ('lrelu', .2 ),
            ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
        ])
    else: raise ValueError('nlayers must be 3 or fewer, not ' + str(nlayers))
    
    return ARCHI

# D = 15
# OUT = 4

# ARCHITECTURES = {
#     "Boubekki":(
#         [('input',D),
#             ('dense', (500, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (500, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (2000, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (2000, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (500, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (500, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#         ),
#     "Wendler":(
#         [('input',D),
#             ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),
#     "10z":(
#         [('input',D),
#             ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (10, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , 10),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),
#     "SmallLayers":(
#         [('input',D),
#             ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),
#     "SmallerLayers":(
#         [('input',D),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (15, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (15, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),
#     "ExtraLayer":(
#         [('input',D),
#           ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (100, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (30, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),
#     "SmallExtraLayer":(
#         [('input',D),
#           ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),
#     "OneIntLayer50":(
#         [('input',D),
#             ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (50, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),
#     "OneIntLayer20":(
#         [('input',D),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),
#     "SmallExtraLayer2":(
#         [('input',D),
#           ('dense', (15, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (60, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (OUT, 'glorot_uniform', 'glorot_normal') ),
#         ],[('input' , OUT),
#             ('dense', (20, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (60, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (15, 'glorot_uniform', 'glorot_normal') ),
#             ('lrelu', .2 ),
#             ('dense', (D, 'glorot_uniform', 'glorot_normal') ),
#         ]
#     ),

# }